import Head from 'next/head'
import SupCus from '../Componants/Tables/SupCusTable.tsx'
import InvSell from '../Componants/Tables/InvSellTable'
export default function Home() {
  const Customer=[{ 
    id:1,
    Name:"Ryad",
    Total:1000,
    Rest: 0,
  },
  { 
    id:2,
    Name:"Rayan",
    Total:5000,
    Rest: 10,
  },
  { 
    id:3,
    Name:"Rayan",
    Total:500,
    Rest: 15,
  },
  { 
    id:4,
    Name:"Mohamed",
    Total:700000,
    Rest: 10000,
  },
  { 
    id:5,
    Name:"Rayan",
    Total:100,
    Rest: 0,
  },
  { 
    id:6,
    Name:"Rayan",
    Total:770,
    Rest: 0,

  },
  { 
    id:7,
    Name:'Rayan',
    Total:0,
    Rest: 0,
  }

]
 const Filtage=[{id:0,Title:'All Customers',Nbr:50},{id:1,Title:'Active Customers',Nbr:30},{id:2,Title:'Inactive Customers',Nbr:20}]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InvSell   Data={Customer} choices={Filtage} title="Customers"  ></InvSell>
    </>
  )
}
